### ISSUE TITLE
Gnome 46

### ISSUE THREAD

**Issue by RafalSkolasinski** [kishorv06/window-state-manager#10]
Support for Gnome 46 (Fedora Linux 40) is missing

![image](https://github.com/kishorviswanathan/window-state-manager/assets/10928117/b4507326-1bd1-4e7a-950e-81fadf99abda)

---

![image](https://github.com/kishorviswanathan/window-state-manager/assets/10928117/e2bca8cd-44c3-4e72-831d-a8a7d92f4a78)

**Comment by kishorviswanathan** [comment]
@RafalSkolasinski The code in this repository supports Gnome 46. I am yet to upload it to the extensions store. Meanwhile you can install it from git.

**Comment by kishorviswanathan** [comment]
Now available for Gnome 46 from extensions store.
