### ISSUE TITLE
Doesn't save position.

### ISSUE THREAD

**Issue by mihalycsaba** [kishorv06/window-state-manager#2]
I have opened an app(Console) and let it run for more than a minute.

**Comment by kishorviswanathan** [comment]
Could you please share more details about the issue ? Also could you try the following.

1. Keep external monitor connected, open an app
2. Wait for atleast 10 seconds
3. Disconnect external monitor and wait for the windows to rearrange.
4. Connect the monitor back and see if app is restored to it's original position.

**Comment by mihalycsaba** [comment]
> Could you please share more details about the issue ? Also could you try the following.
> 
> 1. Keep external monitor connected, open an app
> 2. Wait for atleast 10 seconds
> 3. Disconnect external monitor and wait for the windows to rearrange.
> 4. Connect the monitor back and see if app is restored to it's original position.

I don't use a second monitor, didn't know this extension is only supposed to work with secondary displays.

**Comment by kishorviswanathan** [comment]
Okay, no problem. This extension will only restore state when screen layout changes. There are other extensions that can remember and restore window state on demand. I guess that is what you want.
