### ISSUE TITLE
GNOME 45

### ISSUE THREAD

**Issue by develop7** [kishorv06/window-state-manager#7]
It's out and it's probably breaking this extension

**Comment by galen1423** [comment]
Hello,

Thanks for this useful extension and I hope your work will be ported to GS 45 in a near future. I miss not having custom positions for my windows anymore. ^^

Regards.

**Comment by kishorviswanathan** [comment]
@develop7 @galen1423 The current master already supports GNOME Shell 45. I am currently in the process of getting it approved on https://extensions.gnome.org
